// =========================================================
// GLOSSARY — B.V.Sc UG-Level Tooltip Term Dictionary
// Veterinary Microbiology Studio
// =========================================================
// Usage: glossary.decorate(rootElement) scans rendered HTML
// inside rootElement and wraps known terms with a hover-tooltip.
// Terms are matched longest-first to avoid partial overlap.
// =========================================================

const glossary = {
    // Category mapping for A-Z browsing & filtering
    categories: {
        "General Bacteriology & Morphology": [
            "peptidoglycan",
            "lipopolysaccharide",
            "endotoxin",
            "exotoxin",
            "toxoid",
            "capsule",
            "flagella",
            "pili",
            "fimbriae",
            "endospore",
            "sporulation",
            "germination",
            "biofilm",
            "binary fission",
            "mesosome",
            "teichoic acid",
            "periplasmic space",
            "spheroplast",
            "protoplast",
            "l-form",
            "obligate aerobe",
            "obligate anaerobe",
            "facultative anaerobe",
            "microaerophile",
            "capnophile",
            "psychrophile",
            "mesophile",
            "thermophile",
            "exponential phase",
            "stationary phase",
            "lag phase",
            "death phase",
            "generation time",
            "bacteremia",
            "septicaemia",
            "toxaemia",
            "quorum sensing",
            "dipicolinic acid",
            "volutin granules",
            "metachromatic granules",
            "slime layer",
            "glycocalyx",
            "axial filament",
            "endoflagella",
            "monotrichous",
            "lophotrichous",
            "amphitrichous",
            "peritrichous",
            "magnetosome",
            "carboxysome",
            "porins",
            "lipid a",
            "o-antigen",
            "core polysaccharide",
            "lipoteichoic acid",
            "outer membrane vesicles",
            "siderophore",
            "enterobactin",
            "competence factor",
            "bacteriocin",
            "lysogeny",
            "prophage",
            "pleomorphism",
            "tyndallization",
            "macconkey agar",
            "blood agar",
            "chocolate agar",
            "mannitol salt agar",
            "brilliant green agar",
            "selenite f broth",
            "tetrathionate broth",
            "simmons citrate agar",
            "triple sugar iron agar",
            "indole test",
            "methyl red test",
            "voges-proskauer test",
            "coagulase-negative staphylococci"
        ],
        "Systematic Bacteriology": [
            "coagulase",
            "catalase",
            "hemolysin",
            "alpha-hemolysis",
            "beta-hemolysis",
            "gamma-hemolysis",
            "camp test",
            "strangles",
            "botryomycosis",
            "caseous lymphadenitis",
            "anthrax",
            "blackleg",
            "pulpy kidney",
            "tetanus",
            "tetanospasmin",
            "botulism",
            "acid-fastness",
            "cord factor",
            "tuberculin test",
            "johnin test",
            "paratuberculosis",
            "wooden tongue",
            "lumpy jaw",
            "colibacillosis",
            "swarming motility",
            "glanders",
            "fowl cholera",
            "hemorrhagic septicemia",
            "infectious bovine keratoconjunctivitis",
            "contagious bovine pleuropneumonia",
            "anaplasmosis",
            "heartwater",
            "q fever",
            "mcfadyean's reaction",
            "ascoli's test",
            "protective antigen",
            "lethal factor",
            "edema factor",
            "protein a",
            "staphylococcus pseudointermedius",
            "streptolysin o",
            "streptolysin s",
            "lancefield grouping",
            "internalin",
            "listeriolysin o",
            "shiga toxin",
            "atrophic rhinitis",
            "mallein test",
            "pullorum disease",
            "fowl typhoid",
            "kauffmann-white scheme",
            "swarming phenomenon",
            "urease test",
            "pyocyanin",
            "pyoverdine",
            "melioidosis",
            "shipping fever",
            "leukotoxin",
            "glasser's disease",
            "milk ring test",
            "abortus bang ring test",
            "microscopic agglutination test",
            "avian spirochaetosis",
            "swine dysentery",
            "chlamydia psittaci",
            "elementary body",
            "reticulate body",
            "black disease",
            "necrotic enteritis",
            "braxy",
            "malignant edema",
            "bacillary hemoglobinuria",
            "tyzzer's disease",
            "contagious caprine pleuropneumonia",
            "moraxella bovis",
            "borrelia theileri",
            "campylobacter fetus fetus",
            "campylobacter fetus venerealis",
            "taylorella equigenitalis",
            "mycoplasma bovis",
            "mycoplasma agalactiae",
            "coxiella burnetii",
            "dermatophilus congolensis",
            "pasteurella canis",
            "bacteroides fragilis",
            "actinobacillus pleuropneumoniae",
            "glaesserella parasuis",
            "lawsonia intracellularis"
        ],
        "Veterinary Mycology": [
            "hypha",
            "mycelium",
            "blastoconidia",
            "arthroconidia",
            "chlamydospore",
            "sporangiospore",
            "dimorphic fungi",
            "sabouraud dextrose agar",
            "lactophenol cotton blue",
            "dermatophyte",
            "microsporum",
            "trichophyton",
            "favus",
            "ringworm",
            "malassezia",
            "candidiasis",
            "germ tube test",
            "cryptococcosis",
            "indian ink preparation",
            "aspergillosis",
            "brooder pneumonia",
            "aflatoxin",
            "ochratoxin",
            "zearalenone",
            "fumonisin",
            "ergotism",
            "mycotic mastitis",
            "mycotic abortion",
            "rhinosporidiosis",
            "sporotrichosis",
            "zygomycosis",
            "thallus",
            "pseudohypha",
            "septate hypha",
            "non-septate hypha",
            "conidiophore",
            "sporangium",
            "sterigma",
            "phialide",
            "macroconidia",
            "microconidia",
            "ectothrix",
            "endothrix",
            "wood's lamp",
            "trichophyton verrucosum",
            "trichophyton mentagrophytes",
            "microsporum gypseum",
            "spherule",
            "mycetoma",
            "guttural pouch mycosis",
            "t-2 toxin",
            "microsporum canis",
            "coccidioidomycosis",
            "blastomycosis",
            "histoplasmosis",
            "phaeohyphomycosis",
            "hyalohyphomycosis",
            "mycotoxicosis",
            "citrinin",
            "slaframine",
            "stachybotryotoxicosis",
            "pithomycotoxicosis",
            "macrocyclic trichothecenes"
        ],
        "Microbial Biotechnology & Genetics": [
            "recombinant dna",
            "restriction endonuclease",
            "dna ligase",
            "vector",
            "expression vector",
            "transformation",
            "competent cells",
            "electroporation",
            "transfection",
            "southern blotting",
            "northern blotting",
            "western blotting",
            "pcr",
            "taq polymerase",
            "primer",
            "real-time pcr",
            "reverse transcription pcr",
            "cdna",
            "genomic library",
            "sanger sequencing",
            "dna fingerprinting",
            "rflp",
            "bioinformatics",
            "blast",
            "genbank",
            "biosafety level",
            "plasmid",
            "episome",
            "r-plasmid",
            "f-plasmid",
            "transposon",
            "insertion sequence",
            "conjugation",
            "transduction",
            "generalized transduction",
            "specialized transduction",
            "blue-white screening",
            "multiple cloning site",
            "reporter gene",
            "gfp",
            "nucleic acid hybridization",
            "multiplex pcr",
            "nested pcr",
            "cycle threshold",
            "melting curve analysis",
            "next generation sequencing",
            "illumina sequencing",
            "nanopore sequencing",
            "open reading frame",
            "metagenomics",
            "subunit vaccine",
            "site-directed mutagenesis",
            "sybr green",
            "taqman probe",
            "crispr-cas9",
            "guide rna",
            "pam sequence",
            "pulsed-field gel electrophoresis",
            "dna microarray",
            "plasmid curing",
            "bacteriophage typing",
            "recombinant subunit vaccine",
            "reverse genetics"
        ],
        "Veterinary Immunology & Serology": [
            "bursa of fabricius",
            "thymus",
            "spleen",
            "lymph node",
            "peyer's patches",
            "epitope",
            "hapten",
            "adjuvant",
            "antibody",
            "immunoglobulin",
            "igg",
            "igm",
            "iga",
            "ige",
            "igd",
            "fab fragment",
            "fc fragment",
            "hybridoma",
            "monoclonal antibody",
            "opsonization",
            "agglutination",
            "precipitation",
            "prozone phenomenon",
            "agar gel immunodiffusion",
            "radial immunodiffusion",
            "elisa",
            "mhc",
            "bcr",
            "tcr",
            "complement",
            "membrane attack complex",
            "cytokine",
            "interferon",
            "hypersensitivity",
            "anaphylaxis",
            "arthus reaction",
            "delayed type hypersensitivity",
            "autoimmunity",
            "immunological tolerance",
            "colostrum",
            "passive immunity",
            "active immunity",
            "attenuated vaccine",
            "toxoid vaccine",
            "herd immunity",
            "innate immunity",
            "adaptive immunity",
            "pathogen-associated molecular patterns",
            "pattern recognition receptors",
            "toll-like receptors",
            "respiratory burst",
            "natural killer cells",
            "dendritic cells",
            "heterophil",
            "primary lymphoid organs",
            "secondary lymphoid organs",
            "harderian gland",
            "mucosal-associated lymphoid tissue",
            "regulatory t cells",
            "th1 response",
            "th2 response",
            "gamma-delta t cells",
            "class switching",
            "affinity maturation",
            "secretory component",
            "j-chain",
            "complement classical pathway",
            "complement alternative pathway",
            "complement lectin pathway",
            "virus neutralization test",
            "clonal selection",
            "postzone phenomenon",
            "indirect coombs test",
            "direct coombs test",
            "plaque reduction neutralization",
            "fluorescent antibody test",
            "indirect fluorescent antibody",
            "lateral flow assay",
            "differentiating infected from vaccinated animals",
            "bovine leukocyte adhesion deficiency",
            "immune tolerance",
            "cross-reactivity",
            "superantigen",
            "neonatal isoerythrolysis",
            "seroconversion"
        ],
        "General & Systematic Virology": [
            "virion",
            "capsid",
            "capsomere",
            "nucleocapsid",
            "envelope",
            "peplomer",
            "baltimore classification",
            "syncytium",
            "inclusion body",
            "negri bodies",
            "cytopathic effect",
            "plaque assay",
            "tcid50",
            "embryonated egg",
            "continuous cell line",
            "primary cell culture",
            "viremia",
            "oncogenic virus",
            "reverse transcriptase",
            "antigenic drift",
            "antigenic shift",
            "prion",
            "scrapie",
            "bovine spongiform encephalopathy",
            "rhabdovirus",
            "paramyxovirus",
            "orthomyxovirus",
            "coronavirus",
            "birnavirus",
            "reovirus",
            "picornavirus",
            "flavivirus",
            "asfarvirus",
            "poxvirus",
            "herpesvirus",
            "parvovirus",
            "circovirus",
            "helical symmetry",
            "icosahedral symmetry",
            "eclipse period",
            "burst size",
            "hemagglutinin",
            "neuraminidase",
            "fusion protein",
            "matrix protein",
            "rna-dependent rna polymerase",
            "provirus",
            "viral interference",
            "defective interfering particles",
            "latent viral infection",
            "slow viral infection",
            "vesicular stomatitis",
            "swine vesicular disease",
            "coggins test",
            "lumpy skin disease",
            "aujeszky's disease",
            "infectious canine hepatitis",
            "plaque forming unit",
            "bovine viral diarrhea",
            "classical swine fever",
            "border disease",
            "bovine leukemia virus",
            "caprine arthritis encephalitis",
            "maedi-visna virus",
            "feline calicivirus",
            "bovine ephemeral fever",
            "duck viral hepatitis",
            "feline panleukopenia",
            "canine parvovirus",
            "porcine circovirus",
            "chicken anemia virus",
            "equine viral arteritis"
        ]
    },

    // Full definitions for tooltip overlays & detail drawer
    terms: {
        "peptidoglycan": "Rigid mesh-like polymer of alternating NAG and NAM cross-linked by amino acids, forming the primary structural exoskeleton of bacterial cell walls.",
        "lipopolysaccharide": "Major surface glycolipid of Gram-negative bacterial outer membranes consisting of Lipid A (endotoxin), core oligosaccharide, and O-antigen repeat units.",
        "endotoxin": "Heat-stable toxic lipopolysaccharide component (Lipid A) integral to Gram-negative outer cell walls, released primarily upon bacterial lysis to trigger shock and pyrexia.",
        "exotoxin": "Diffusible, highly potent protein toxin secreted by living Gram-positive or Gram-negative bacteria into surrounding tissues (e.g. tetanus, botulinum, anthrax toxins).",
        "toxoid": "Inactivated exotoxin chemically treated (typically with formaldehyde) or heat-denatured to eliminate toxicity while retaining complete immunogenicity for vaccination.",
        "capsule": "Gelatinous glycocalyx layer exterior to bacterial cell wall (usually polysaccharide, poly-D-glutamate in B. anthracis) mediating anti-phagocytic virulence.",
        "flagella": "Helical filamentous protein appendages driven by rotary basal bodies that provide active motility to bacteria.",
        "pili": "Hair-like surface protein appendages (pilin); specialised F-pili mediate horizontal gene transfer during bacterial conjugation.",
        "fimbriae": "Short, numerous filamentous protein projections on bacterial surfaces facilitating specific adherence to host mucosal epithelial cells.",
        "endospore": "Dormant, highly resistant, dehydrated resting structure produced intracellularly by Bacillus and Clostridium during harsh environmental conditions.",
        "sporulation": "Multi-stage process by which vegetative bacterial cells form resistant endospores in response to nutrient exhaustion or desiccation.",
        "germination": "Outgrowth of a dormant bacterial endospore into a metabolically active vegetative cell upon exposure to favorable nutritional conditions and heat activation.",
        "biofilm": "Structured community of bacterial cells enclosed in a self-produced extracellular polymeric substance (EPS) matrix adherent to biological or inert surfaces.",
        "binary fission": "Asexual reproductive division of a single bacterial cell into two genetically identical daughter cells following genomic replication.",
        "mesosome": "Invagination of bacterial plasma membrane involved in cellular respiration, secretion, and cell division cross-wall formation.",
        "teichoic acid": "Glycerol or ribitol phosphate polymers embedded in the thick peptidoglycan layer of Gram-positive bacterial cell walls.",
        "periplasmic space": "Gel-filled compartment located between the cytoplasmic membrane and outer membrane of Gram-negative bacteria containing enzymes and transport proteins.",
        "spheroplast": "Gram-negative bacterium partially stripped of its peptidoglycan layer by lysozyme or penicillin but retaining its outer membrane.",
        "protoplast": "Gram-positive bacterial cell completely devoid of its cell wall, bounded solely by its cytoplasmic membrane and osmotically fragile.",
        "l-form": "Wall-deficient bacterial variant capable of growth and replication, often induced by antibiotic stress against cell wall synthesis.",
        "obligate aerobe": "Organism that strictly requires atmospheric oxygen for aerobic cellular respiration and survival (e.g. Mycobacterium, Pseudomonas).",
        "obligate anaerobe": "Organism unable to utilize oxygen and poisoned by toxic oxygen radicals due to lack of catalase and superoxide dismutase (e.g. Clostridium).",
        "facultative anaerobe": "Organism capable of growing in the presence or absence of oxygen, utilizing aerobic respiration or fermentation (e.g. E. coli, Staphylococcus).",
        "microaerophile": "Bacterium requiring reduced levels of oxygen (2–10%) and elevated CO2 for optimal growth (e.g. Campylobacter, Brucella).",
        "capnophile": "Microorganism that thrives in the presence of high concentrations of carbon dioxide (5–10% CO2).",
        "psychrophile": "Cold-adapted microorganism capable of growth and reproduction at cold temperatures ranging from 0°C to 15°C.",
        "mesophile": "Microorganism with optimum growth temperature between 20°C and 45°C, including the vast majority of mammalian pathogens.",
        "thermophile": "Heat-tolerant microorganism flourishing at elevated temperatures between 45°C and 70°C.",
        "exponential phase": "Logarithmic growth phase during which bacteria divide at their maximal constant rate, highly susceptible to cell-wall acting antibiotics.",
        "stationary phase": "Culture growth phase where cell multiplication equals cell death rate due to nutrient depletion and toxic metabolite accumulation.",
        "lag phase": "Initial period following bacterial inoculation where cells adjust to media and synthesize enzymes with no increase in cell number.",
        "death phase": "Decline phase where rate of bacterial cell death exceeds cell division due to exhausted resources and severe toxic accumulation.",
        "generation time": "Time required for a bacterial population to double in number through binary fission under optimal physiological conditions.",
        "bacteremia": "Transient presence of viable bacteria circulating in the bloodstream without active multiplication.",
        "septicaemia": "Systemic bacteremia with active multiplication of pathogenic bacteria and dissemination of their toxic products in the blood, leading to high fever and collapse.",
        "toxaemia": "Presence and systemic dissemination of bacterial toxins in the blood circulation, with or without localized bacterial multiplication.",
        "quorum sensing": "Bacterial cell-to-cell communication mechanism utilizing secreted autoinducer signaling molecules to coordinate gene expression and virulence as population density increases.",
        "coagulase": "Enzyme produced by Staphylococcus aureus that converts host soluble fibrinogen into insoluble fibrin clots, insulating bacteria from host phagocytes.",
        "catalase": "Enzyme that decomposes toxic hydrogen peroxide into water and oxygen; distinguishes Staphylococci (positive) from Streptococci (negative).",
        "hemolysin": "Lipid- or protein-based toxin produced by bacteria that causes lysis of host red blood cell membranes.",
        "alpha-hemolysis": "Partial, green or brownish discoloration and incomplete clearing of red blood cells around colonies on blood agar (e.g. Streptococcus pneumoniae).",
        "beta-hemolysis": "Complete, clear zone of erythrocyte lysis around bacterial colonies on blood agar (e.g. Streptococcus equi, Staphylococcus aureus).",
        "gamma-hemolysis": "Absence of hemolysis or clearing on blood agar media around bacterial colonies.",
        "camp test": "Christie-Atkins-Munch-Petersen test demonstrating synergistic enhanced beta-hemolysis when Group B Streptococci (S. agalactiae) meet S. aureus beta-lysin on blood agar.",
        "strangles": "Acute, highly contagious equine upper respiratory infection caused by Streptococcus equi subsp. equi, characterized by purulent lymphadenitis of submandibular lymph nodes.",
        "botryomycosis": "Chronic granulomatous suppurative bacterial infection usually caused by Staphylococcus aureus, producing characteristic macroscopic granules in equine tissues.",
        "caseous lymphadenitis": "Chronic contagious disease of sheep and goats caused by Corynebacterium pseudotuberculosis, characterized by suppurative laminated 'onion-ring' caseous abscesses in lymph nodes.",
        "anthrax": "Peracute, zoonotic, septicemic disease of herbivores caused by Bacillus anthracis, presenting with sudden death, splenomegaly, and non-clotting dark blood from orifices.",
        "blackleg": "Acute, non-contagious gas gangrene of skeletal muscle in cattle caused by Clostridium chauvoei, resulting in crepitant swelling and lameness.",
        "pulpy kidney": "Acute enterotoxemia in sheep caused by Clostridium perfringens type D epsilon toxin, characterized by rapid post-mortem autolysis of renal tissue and glucosuria.",
        "tetanus": "Neurological intoxication caused by tetanospasmin of Clostridium tetani, characterized by persistent spastic muscle paralysis and hyperreflexia.",
        "tetanospasmin": "Potent neurotoxin produced by Clostridium tetani that retrograde-transports to the CNS and cleaves synaptobrevin, preventing release of inhibitory GABA and glycine.",
        "botulism": "Flaccid neuromuscular paralysis caused by ingestion of preformed botulinum neurotoxin from Clostridium botulinum, preventing acetylcholine release at motor endplates.",
        "acid-fastness": "Physical property of bacteria having cell walls rich in mycolic acids (e.g. Mycobacterium) that resist decolorization by acid-alcohol after carbol fuchsin staining.",
        "cord factor": "Trehalose 6,6'-dimycolate, an important glycolipid virulence factor on virulent Mycobacterium tuberculosis strains responsible for serpentine cord-like growth.",
        "tuberculin test": "Delayed-type hypersensitivity (DTH) intradermal diagnostic skin test using purified protein derivative (PPD) to detect cellular immune sensitization to Mycobacterium bovis.",
        "johnin test": "Diagnostic intradermal hypersensitivity test using M. paratuberculosis culture filtrate extract (Johnin PPD) to detect Johne's disease in cattle.",
        "paratuberculosis": "Johne's disease; chronic granulomatous enteritis in ruminants caused by Mycobacterium avium subsp. paratuberculosis, causing intractable diarrhea and emaciation.",
        "wooden tongue": "Chronic granulomatous infection of the bovine tongue and soft tissues caused by Actinobacillus lignieresii, resulting in severe induration and dysphagia.",
        "lumpy jaw": "Chronic rarefying osteomyelitis of the bovine mandible and maxilla caused by Actinomyces bovis, characterized by bone proliferation and sinus drainage with sulfur granules.",
        "colibacillosis": "Infection caused by pathogenic strains of Escherichia coli, manifesting as neonatal diarrhea, edema disease in pigs, or systemic septicemia in poultry and calves.",
        "swarming motility": "Coordinated multicellular movement across solid agar surface producing concentric wave-like growth patterns, characteristic of Proteus species.",
        "glanders": "Fatal, contagious zoonotic disease of solipeds caused by Burkholderia mallei, producing nodular ulcers in the respiratory tract and cutaneous lymphatic chain ('farcy').",
        "fowl cholera": "Highly contagious avian pasteurellosis caused by Pasteurella multocida, presenting with septicemia, high mortality, and cyanosis of comb and wattles.",
        "hemorrhagic septicemia": "Acute, fatal septicemic disease of cattle and water buffalo caused by Pasteurella multocida serotypes B:2 and E:2, marked by high fever and submandibular edema.",
        "infectious bovine keratoconjunctivitis": "'Pinkeye'; acute contagious ocular infection of cattle caused by Moraxella bovis, characterized by corneal ulceration, photophobia, and opacity.",
        "contagious bovine pleuropneumonia": "Severe contagious pulmonary disease of cattle caused by Mycoplasma mycoides subsp. mycoides, characterized by fibrinous pleuropneumonia and marbled lung appearance.",
        "anaplasmosis": "Tick-borne rickettsial infection of ruminants caused by Anaplasma marginale, causing severe extravascular hemolytic anemia and icterus without hemoglobinuria.",
        "heartwater": "Tick-borne rickettsial disease of ruminants caused by Ehrlichia ruminantium, presenting with nervous signs, hydropericardium ('heartwater'), and pulmonary edema.",
        "q fever": "Zoonotic infection caused by Coxiella burnetii, an obligate intracellular bacterium resistant to drying, causing reproductive failure and abortion in ruminants.",
        "hypha": "Microscopic branching thread-like tubular filament of a fungal mould, either septate or aseptate (coenocytic).",
        "mycelium": "Intertwined, macroscopic vegetative or aerial mass composed of numerous hyphal filaments constituting the thallus of a fungus.",
        "blastoconidia": "Asexual fungal spores formed by the budding process from a parent yeast or fungal cell (e.g. Candida, Malassezia).",
        "arthroconidia": "Asexual fungal spores produced by fragmentation and thickening of pre-existing vegetative hyphal compartments (e.g. Dermatophytes, Coccidioides).",
        "chlamydospore": "Thick-walled, highly resistant resting asexual fungal spore formed terminal or intercalary within a vegetative hypha (e.g. Candida albicans).",
        "sporangiospore": "Asexual fungal spore produced within an enclosed, sac-like structure termed a sporangium (characteristic of Zygomycetes).",
        "dimorphic fungi": "Fungi capable of transitioning between two morphological states: mould phase at environmental temperatures (25°C) and yeast phase at host body temperature (37°C).",
        "sabouraud dextrose agar": "Selective culture medium with acidic pH (5.6) and high dextrose content for the isolation and cultivation of pathogenic fungi and yeasts.",
        "lactophenol cotton blue": "Mounting and staining fluid for fungal microscopy: phenol kills cells, lactic acid preserves structure, and cotton blue stains chitin and cellulose in fungal walls.",
        "dermatophyte": "Mould fungus capable of invading keratinized tissues (skin, hair, claws, feathers) using extracellular keratinases (Microsporum, Trichophyton).",
        "microsporum": "Genus of dermatophytes characteristically producing abundant large, rough-walled, multi-septate macroconidia (e.g. M. canis causes ringworm in cats/dogs).",
        "trichophyton": "Genus of dermatophytes producing predominantly smooth, thin-walled microconidia and rare pencil-shaped macroconidia (e.g. T. verrucosum causes ringworm in cattle).",
        "favus": "Severe, chronic dermatophyte infection producing yellow cup-shaped crusts ('scutula') on skin and feathers, caused by Microsporum gallinae or Trichophyton schoenleinii.",
        "ringworm": "Common dermatophytosis of domestic animals characterized by circular, expanding alopecic patches, crusting, and broken hairs.",
        "malassezia": "Lipophilic opportunistic yeast causing pruritic otitis externa and dermatitis in dogs (primarily Malassezia pachydermatis).",
        "candidiasis": "Opportunistic fungal infection ('thrush') caused by Candida albicans affecting mucous membranes of digestive and urogenital tracts.",
        "germ tube test": "Rapid diagnostic screen for Candida albicans: yeast forms germ tubes when incubated in mammalian serum at 37°C for 2–3 hours.",
        "cryptococcosis": "Subacute or chronic fungal infection caused by encapsulated yeast Cryptococcus neoformans, targeting feline nasal cavity, skin, and central nervous system.",
        "indian ink preparation": "Negative staining diagnostic technique where colloidal carbon particles are excluded by the prominent mucopolysaccharide capsule of Cryptococcus neoformans.",
        "aspergillosis": "Infection caused by Aspergillus species (mainly A. fumigatus), causing mycotic pneumonia in poultry ('brooder pneumonia') and nasal plaques in dogs.",
        "brooder pneumonia": "Acute, fatal pulmonary aspergillosis of young chicks and poults caused by inhaling spore-laden dust from contaminated litter or incubators.",
        "aflatoxin": "Hepatotoxic and carcinogenic mycotoxins produced by Aspergillus flavus and Aspergillus parasiticus on stored grains, causing hepatic necrosis and lipidosis.",
        "ochratoxin": "Nephrotoxic mycotoxin produced by Aspergillus and Penicillium species, causing porcine nephropathy and visceral gout in poultry.",
        "zearalenone": "Estrogenic mycotoxin produced by Fusarium species on maize, causing vulvovaginitis, rectal prolapse, and reproductive disorders in swine.",
        "fumonisin": "Mycotoxin produced by Fusarium verticillioides that inhibits sphingolipid biosynthesis, causing equine leukoencephalomalacia and porcine pulmonary edema.",
        "ergotism": "Mycotoxicosis caused by ingesting sclerotia of Claviceps purpurea on cereal grasses containing ergot alkaloids, leading to peripheral gangrene and agalactia.",
        "mycotic mastitis": "Chronic, refractory inflammation of the bovine mammary gland caused by fungal agents such as Candida, Aspergillus, or Prototheca.",
        "mycotic abortion": "Sporadic bovine abortion occurring in the second or third trimester caused by haematogenous spread of Aspergillus or Zygomycetes to the placenta.",
        "rhinosporidiosis": "Chronic granulomatous infection of mucosal surfaces (chiefly nasal cavity) in dogs, horses, and cattle, producing vascular, polypoid masses with sporangia.",
        "sporotrichosis": "Chronic, granulomatous subcutaneous and lymphatic fungal infection caused by dimorphic Sporothrix schenckii ('rose gardener's disease') in cats and horses.",
        "zygomycosis": "Invasive fungal infection caused by mucoralean moulds (Mucor, Rhizopus, Absidia) with broad, non-septate hyphae exhibiting predilection for vascular invasion.",
        "recombinant dna": "Genetically engineered DNA molecules created in vitro by joining genetic sequences from distinct biological sources.",
        "restriction endonuclease": "Bacterial enzyme that cleaves double-stranded DNA at specific palindromic recognition sequences, generating sticky or blunt ends for gene cloning.",
        "dna ligase": "Enzyme that covalently seals single-stranded nicks in double-stranded DNA by catalyzing phosphodiester bond formation between 3'-OH and 5'-phosphate ends.",
        "vector": "Autonomous DNA molecule (plasmid, virus, cosmid) used as a vehicle to artificially carry foreign genetic material into another cell for replication or expression.",
        "expression vector": "Cloning plasmid engineered with strong promoter, ribosome binding site, and termination sequences to achieve high-level transcription and translation of cloned genes.",
        "transformation": "Uptake and functional incorporation of naked exogenous DNA molecules by competent bacterial cells from their surrounding environment.",
        "competent cells": "Bacterial cells chemically or physically treated (e.g. cold CaCl2 or electroporation) to transiently enhance membrane permeability for DNA uptake.",
        "electroporation": "Technique employing high-voltage electrical pulses to create transient nanometer-sized pores in cell membranes, enabling foreign DNA entry.",
        "transfection": "Introduction of foreign nucleic acids into eukaryotic cells by non-viral physical, chemical, or lipid-mediated means.",
        "southern blotting": "Molecular technique for transferring electrophoretically separated DNA fragments from an agarose gel to a membrane filter for hybridisation detection.",
        "northern blotting": "Laboratory technique for separating and immobilizing RNA molecules on nylon membranes to measure gene expression levels with specific nucleic acid probes.",
        "western blotting": "Analytical method for detecting specific proteins in tissue extracts by gel electrophoresis, membrane transfer, and enzyme-labeled antibody probing.",
        "pcr": "Polymerase chain reaction; in vitro enzymatic technique for exponential amplification of specific target DNA sequences through repeated cycles of denaturation, annealing, and extension.",
        "taq polymerase": "Thermostable DNA polymerase isolated from thermophilic bacterium Thermus aquaticus capable of withstanding the 95°C denaturation step in PCR.",
        "primer": "Short, single-stranded oligonucleotide sequence (18–25 nt) designed to hybridize specifically to flanking target DNA and prime DNA polymerase synthesis.",
        "real-time pcr": "Quantitative PCR (qPCR) measuring amplicon accumulation continuously during cycling via fluorescent dyes or probe-based chemistry (TaqMan).",
        "reverse transcription pcr": "Molecular method (RT-PCR) utilizing reverse transcriptase enzyme to synthesize cDNA from RNA templates prior to standard PCR amplification.",
        "cdna": "Complementary DNA synthesized enzymatically from an mRNA template by reverse transcriptase, representing the expressed exon sequences without introns.",
        "genomic library": "Collection of cloned DNA fragments representing the entire genomic sequence of a particular organism inserted into cloning vectors.",
        "sanger sequencing": "Dideoxy chain termination method for determining exact nucleotide order in DNA using 2',3'-dideoxynucleoside triphosphates (ddNTPs).",
        "dna fingerprinting": "Molecular identification profiling based on polymorphic tandem repeat sequences (VNTRs/STRs) or restriction fragment profiles unique to individual organisms.",
        "rflp": "Restriction fragment length polymorphism; genetic variation in DNA fragment patterns generated by specific restriction endonuclease digestion.",
        "bioinformatics": "Interdisciplinary field combining computational tools, mathematics, and molecular biology to acquire, store, analyze, and interpret biological data.",
        "blast": "Basic Local Alignment Search Tool; algorithmic software comparing query protein or nucleotide sequences against vast international sequence databases.",
        "genbank": "Comprehensive NIH/NCBI genetic sequence database containing publicly accessible annotated collections of all DNA and RNA sequences.",
        "biosafety level": "Hierarchical biocontainment containment levels (BSL-1 to BSL-4) specifying laboratory facilities, safety equipment, and operating practices.",
        "bursa of fabricius": "Primary lymphoid organ in avian species situated on the dorsal wall of the cloaca, responsible for B-cell maturation and immunoglobulin gene diversification.",
        "thymus": "Primary bilobed lymphoid organ situated in the anterior mediastinum and neck, responsible for T-lymphocyte maturation and positive/negative selection.",
        "spleen": "Largest secondary lymphoid organ, containing red pulp for erythrocyte filtration and white pulp (PALS) for immune surveillance against blood-borne pathogens.",
        "lymph node": "Encapsulated secondary lymphoid organ filtering lymph, organized into outer cortex (B-cells), paracortex (T-cells), and inner medulla (plasma cells).",
        "peyer's patches": "Organized aggregated lymphoid follicles embedded within the lamina propria and submucosa of the small intestine, monitoring gut microbial antigens.",
        "epitope": "Antigenic determinant; specific molecular surface feature or sequence of an antigen recognized directly by an antibody paratope, BCR, or TCR.",
        "hapten": "Small, non-immunogenic chemical molecule capable of binding antibodies but unable to stimulate an immune response alone unless conjugated to a carrier protein.",
        "adjuvant": "Substance added to vaccines that non-specifically enhances the magnitude, duration, and quality of antigen-specific immune responses.",
        "antibody": "Y-shaped immunoglobulin glycoprotein secreted by plasma cells in response to foreign immunogens, neutralizing pathogens and tagging them for destruction.",
        "immunoglobulin": "Class of structurally related globular glycoproteins (IgG, IgM, IgA, IgE, IgD) functioning as circulating antibodies or membrane-bound B-cell receptors.",
        "igg": "Predominant immunoglobulin isotype in mammalian serum and colostrum providing long-term systemic immunity, opsonization, and complement activation.",
        "igm": "Pentameric high-molecular-weight immunoglobulin produced first during primary immune responses, highly efficient at agglutination and complement fixation.",
        "iga": "Dimeric mucosal immunoglobulin equipped with a secretory component, protecting respiratory, gastrointestinal, and urogenital mucosal surfaces.",
        "ige": "Immunoglobulin isotype that binds high-affinity Fc receptors on mast cells and basophils, mediating Type I hypersensitivity and anti-helminth immunity.",
        "igd": "Co-expressed with IgM on the surface of mature naive B-lymphocytes as an antigen receptor, present in negligible concentrations in serum.",
        "fab fragment": "Antigen-binding fragment produced by papain cleavage of an immunoglobulin monomer, containing variable heavy and light chains.",
        "fc fragment": "Crystallizable constant fragment of an antibody molecule mediating biological effector functions (complement binding, Fc receptor attachment on phagocytes).",
        "hybridoma": "Immortal hybrid cell created by fusing an antigen-primed antibody-producing B-lymphocyte with a cancerous myeloma cell, producing monoclonal antibodies.",
        "monoclonal antibody": "Homogeneous population of antibody molecules produced by a single hybridoma clone, binding with identical affinity to one specific epitope.",
        "opsonization": "Immune process coating foreign pathogens with opsonins (IgG antibodies or C3b complement) to greatly facilitate recognition and engulfment by phagocytes.",
        "agglutination": "Visible clumping reaction occurring when multivalent antibodies cross-link particulate antigens (bacteria or erythrocytes) into visible aggregates.",
        "precipitation": "Serological reaction where soluble antibodies cross-link soluble antigens at an optimal equivalence ratio, forming an insoluble visible precipitate.",
        "prozone phenomenon": "False-negative serological precipitation or agglutination test result caused by extreme antibody excess preventing lattice formation.",
        "agar gel immunodiffusion": "Ouchterlony AGID; serological diagnostic test where antigen and antibody diffuse toward each other through agar to form a precipitin line of identity.",
        "radial immunodiffusion": "Mancini technique; quantitative serological assay measuring the diameter of precipitation rings formed as antigen diffuses into antibody-impregnated agar.",
        "elisa": "Enzyme-Linked Immunosorbent Assay; sensitive diagnostic serological method utilizing enzyme-labeled antibodies and chromogenic substrates to quantify antigens or antibodies.",
        "mhc": "Major Histocompatibility Complex; cell-surface glycoproteins presenting processed peptide fragments to T-cells (MHC-I presents to CD8+, MHC-II to CD4+).",
        "bcr": "B-cell receptor; membrane-bound immunoglobulin monomer paired with Ig-alpha/Ig-beta signaling heterodimers on B-lymphocyte membranes.",
        "tcr": "T-cell receptor; heterodimeric surface protein (alpha-beta or gamma-delta) associated with CD3 complex on T-lymphocytes that recognizes peptide-MHC complexes.",
        "complement": "System of heat-labile plasma proteins and membrane receptors activating in a cascading sequence to mediate opsonization, inflammation, and cell lysis.",
        "membrane attack complex": "Terminal complement complex (C5b-6-7-8-9) that inserts into microbial lipid bilayers to create transmembrane pores, inducing osmotic lysis.",
        "cytokine": "Low-molecular-weight soluble regulatory signaling protein secreted by immune and stromal cells mediating intercellular communication and inflammation.",
        "interferon": "Family of antiviral and immunomodulatory cytokines (IFN-alpha, IFN-beta, IFN-gamma) induced during viral infection that stimulate an intracellular antiviral state.",
        "hypersensitivity": "Exaggerated or inappropriate immune response to an antigen that results in tissue damage, categorized into Coombs & Gell Types I to IV.",
        "anaphylaxis": "Acute, life-threatening systemic Type I hypersensitivity reaction characterized by widespread mast cell degranulation, bronchoconstriction, and shock.",
        "arthus reaction": "Localized Type III hypersensitivity response occurring in tissues with high levels of circulating antibody when challenged with intradermal antigen.",
        "delayed type hypersensitivity": "Cell-mediated Type IV hypersensitivity reaction taking 24–72 hours to manifest, mediated by sensitized CD4+ Th1 cells and recruited macrophages.",
        "autoimmunity": "Pathological immune response wherein the host immune system generates antibodies or cytotoxic T-cells targeting its own self-antigens.",
        "immunological tolerance": "State of specific unresponsiveness of the immune system to substances (particularly self-antigens) that would otherwise elicit an immune attack.",
        "colostrum": "First milk secreted postpartum by the mammary gland, densely concentrated with maternal immunoglobulins (predominantly IgG) critical for passive neonatal immunity.",
        "passive immunity": "Transfer of active humoral immunity in the form of pre-made antibodies from an immune donor to a non-immune recipient (e.g. colostrum or antisera).",
        "active immunity": "Immunity stimulated directly in an individual following exposure to a live pathogen or immunization with a vaccine antigen.",
        "attenuated vaccine": "Vaccine containing viable microorganisms whose virulence has been deliberately weakened through laboratory passaging while retaining immunogenicity.",
        "toxoid vaccine": "Vaccine containing a detoxified bacterial exotoxin that stimulates protective neutralizing antitoxin antibodies.",
        "herd immunity": "Indirect protection of susceptible individuals within a population when a critical proportion of the population is immune to an infectious agent.",
        "virion": "Complete, infectious, extracellular physical viral particle consisting of a nucleic acid genome surrounded by a protein capsid and optional envelope.",
        "capsid": "Symmetrical protein shell enclosing and protecting the viral nucleic acid genome from extracellular environmental inactivation.",
        "capsomere": "Morphological protein subunit visible under electron microscopy that self-assembles to form the viral capsid structure.",
        "nucleocapsid": "Integrated structural complex composed of the viral nucleic acid genome enclosed directly within its protein capsid shell.",
        "envelope": "Host-derived lipid bilayer membrane surrounding certain viral capsids, acquired by budding through host cellular membranes and studded with viral glycoproteins.",
        "peplomer": "Glycoprotein spike projecting outward from the lipid bilayer envelope of enveloped viruses, mediating host receptor binding and membrane fusion.",
        "baltimore classification": "Virological classification scheme grouping viruses into seven distinct classes based on genome type (DNA/RNA, ss/ds) and pathway to mRNA synthesis.",
        "syncytium": "Multinucleated giant cell formed by the fusion of adjacent host cell membranes induced by viral fusion glycoproteins (e.g. Paramyxoviridae).",
        "inclusion body": "Discrete microscopic aggregates of viral proteins or virions visible within the host cell cytoplasm or nucleus during specific viral infections.",
        "negri bodies": "Pathognomonic eosinophilic intracytoplasmic viral inclusion bodies found in neurons of animals infected with Rabies virus (Rhabdoviridae).",
        "cytopathic effect": "Morphological changes, structural alterations, and degenerative destruction observable in host cell cultures resulting from viral infection (CPE).",
        "plaque assay": "Quantitative virological assay measuring the number of infectious viral units (PFU) based on focal areas of cell lysis in a monolayer culture.",
        "tcid50": "Tissue Culture Infectious Dose 50; statistical dilution of virus required to produce cytopathic effects in 50% of inoculated cell culture replicates.",
        "embryonated egg": "Fertile avian egg (usually 9–11 day old chicken embryo) utilized for the isolation, propagation, and titration of animal viruses.",
        "continuous cell line": "Immortalized cell culture capable of infinite in vitro passages without senescence (e.g. Vero, BHK-21, MDBK).",
        "primary cell culture": "Cell culture established directly from freshly dissociated embryonic or animal tissues, surviving for only a finite number of passages in vitro.",
        "viremia": "Dissemination and presence of infectious viral particles circulating within the host bloodstream.",
        "oncogenic virus": "Virus capable of transforming normal host cells into malignant neoplastic cells by integrating viral oncogenes or perturbing cell cycle controls.",
        "reverse transcriptase": "RNA-dependent DNA polymerase enzyme encoded by retroviruses that transcribes single-stranded viral RNA into double-stranded complementary DNA.",
        "antigenic drift": "Minor, gradual point mutations in viral surface glycoprotein genes (e.g. influenza hemagglutinin) that allow escape from existing host immunity.",
        "antigenic shift": "Major, abrupt genetic reassortment between distinct influenza viral strains yielding novel surface glycoproteins capable of causing pandemics.",
        "prion": "Small, infectious, proteinaceous particle devoid of nucleic acid; the misfolded isoform (PrPSc) induces pathogenic conformational change in normal host PrPC.",
        "scrapie": "Transmissible spongiform encephalopathy of sheep and goats characterized by pruritus, ataxia, wasting, and bilateral vacuolation of brainstem neurons.",
        "bovine spongiform encephalopathy": "'Mad Cow Disease'; fatal neurodegenerative prion disease of cattle caused by feeding meat-and-bone meal contaminated with scrapie or BSE prions.",
        "rhabdovirus": "Bullet-shaped, enveloped negative-sense single-stranded RNA virus family including Rabies virus and Bovine Ephemeral Fever virus.",
        "paramyxovirus": "Enveloped, pleomorphic negative-sense single-stranded RNA virus family responsible for Newcastle disease, Rinderpest, PPR, and Canine Distemper.",
        "orthomyxovirus": "Segmented, enveloped negative-sense single-stranded RNA virus family encoding hemagglutinin and neuraminidase, causing Avian, Equine, and Swine Influenza.",
        "coronavirus": "Large, enveloped positive-sense single-stranded RNA virus family with club-shaped surface spikes, causing Infectious Bronchitis in poultry and TGE in pigs.",
        "birnavirus": "Non-enveloped, bi-segmented double-stranded RNA virus family containing Infectious Bursal Disease Virus (IBDV / Gumboro disease).",
        "reovirus": "Non-enveloped icosahedral double-stranded RNA virus family with segmented genomes, including Bluetongue Virus and African Horse Sickness Virus.",
        "picornavirus": "Small, non-enveloped positive-sense single-stranded RNA virus family containing Aphthovirus, the causative agent of Foot-and-Mouth Disease (FMD).",
        "flavivirus": "Enveloped positive-sense single-stranded RNA virus family containing Pestiviruses: Classical Swine Fever Virus (Hog Cholera) and Bovine Viral Diarrhea Virus.",
        "asfarvirus": "Large, enveloped double-stranded DNA virus family containing African Swine Fever Virus (ASFV), the only known DNA arbovirus of vertebrates.",
        "poxvirus": "Large, complex brick-shaped double-stranded DNA virus family that replicates in host cytoplasm, causing Sheep Pox, Goat Pox, and Lumpy Skin Disease.",
        "herpesvirus": "Enveloped, icosahedral double-stranded DNA virus family capable of establishing life-long latency in sensory ganglia (IBR/BHV-1, Marek's disease, ILTV).",
        "parvovirus": "Small, non-enveloped, resilient single-stranded DNA virus family with affinity for rapidly dividing host cells, causing severe feline and canine enteritis.",
        "circovirus": "Smallest non-enveloped circular single-stranded DNA viruses of vertebrates, causing Chicken Anemia and Porcine Circovirus Associated Disease (PCVAD).",
        "dipicolinic acid": "Spore-specific organic acid complexed with calcium ions (calcium dipicolinate) in bacterial core, providing extreme thermal and chemical heat resistance.",
        "volutin granules": "Inorganic polyphosphate inclusion reserves (Babes-Ernst granules) characteristic of Corynebacterium diphtheriae and related actinomycetes.",
        "metachromatic granules": "Intracellular polyphosphate storage bodies that stain reddish-purple with blue basic dyes (Neisser or Albert stain) due to polychromatic shift.",
        "slime layer": "Loose, unorganized, water-soluble polysaccharide secretion surrounding bacterial cells, easily washed off compared to a rigid structural capsule.",
        "glycocalyx": "Network of sticky polysaccharide and polypeptide fibrils extending from bacterial outer surface mediating adherence to biological tissues and medical catheters.",
        "axial filament": "Bundles of specialized periplasmic endoflagella located between peptidoglycan and outer membrane that produce corkscrew motility in spirochaetes.",
        "endoflagella": "Internal flagella anchored at cell poles within the periplasmic space of spirochetes (Leptospira, Borrelia, Treponema) driving undulating movement.",
        "monotrichous": "Bacterial flagellar arrangement characterized by a single polar flagellum at one end of the cell (e.g. Pseudomonas aeruginosa).",
        "lophotrichous": "Bacterial flagellar arrangement consisting of a cluster or tuft of flagella originating from one or both cell poles.",
        "amphitrichous": "Bacterial flagellar arrangement possessing a single flagellum (or tuft) projecting from each of the two opposite polar ends.",
        "peritrichous": "Bacterial flagellar morphology where flagella are distributed uniformly across the entire exterior cell surface (e.g. Proteus, Salmonella).",
        "magnetosome": "Intracellular membrane-bound lipid vesicle containing magnetic iron crystals (magnetite, Fe3O4) allowing magnetotactic bacteria to orient along geomagnetic field lines.",
        "carboxysome": "Protein-enclosed bacterial microcompartment packed with ribulose-1,5-bisphosphate carboxylase/oxygenase (RuBisCO) for carbon dioxide fixation.",
        "porins": "Transmembrane water-filled trimeric beta-barrel proteins in Gram-negative outer membranes governing passive diffusion of hydrophilic molecules.",
        "lipid a": "Phosphorylated glucosamine disaccharide lipid anchor of Gram-negative lipopolysaccharide responsible for endotoxic shock, fever, and DIC.",
        "o-antigen": "Surface-exposed variable repeating oligosaccharide chain of lipopolysaccharide conferring somatic serotype specificity to Enterobacteriaceae.",
        "core polysaccharide": "Conserved branched oligosaccharide domain linking inner Lipid A to outer O-antigen chain within Gram-negative lipopolysaccharide.",
        "lipoteichoic acid": "Glycerol phosphate polymer linked to membrane lipids in Gram-positive bacterial cell walls, acting as a major surface adhesin and cytokine trigger.",
        "outer membrane vesicles": "Spherical nanovesicles (20-250 nm) naturally budded from Gram-negative outer membranes transporting virulence factors, DNA, and signaling molecules.",
        "siderophore": "High-affinity ferric iron-chelating molecule synthesized and secreted by bacteria (e.g. enterobactin) to scavenge iron from host lactoferrin and transferrin.",
        "enterobactin": "Extremely high-affinity catecholate siderophore produced by Escherichia coli and Salmonella enterica for scavenging host iron.",
        "competence factor": "Extracellular peptide pheromone secreted by bacteria during high cell density that stimulates natural genetic transformation.",
        "bacteriocin": "Proteinaceous antibacterial toxin produced by bacteria to inhibit the growth of closely related or competing bacterial strains (e.g. colicins).",
        "lysogeny": "Non-lytic stable bacterial state where temperate bacteriophage genome integrates into the bacterial chromosome and persists as a prophage.",
        "prophage": "Latent, non-infectious form of a temperate bacteriophage genome integrated into the host bacterial chromosome or replicating as a circular plasmid.",
        "mcfadyean's reaction": "Diagnostic polychrome methylene blue staining of Bacillus anthracis blood smears showing blue bacilli surrounded by prominent pinkish-purple capsules.",
        "ascoli's test": "Thermostable precipitation ring test used to diagnose anthrax in decaying animal carcasses or hides by reacting tissue extract against anthrax antiserum.",
        "protective antigen": "83-kDa receptor-binding protein of Bacillus anthracis tripartite exotoxin that binds host capillary cells and translocates LF and EF inside.",
        "lethal factor": "Zinc metalloprotease component of Anthrax toxin that cleaves host MAP-kinase kinases (MAPKKs), causing macrophage apoptosis and circulatory collapse.",
        "edema factor": "Calmodulin-dependent adenylate cyclase component of Anthrax toxin that elevates intracellular cAMP, causing severe tissue edema.",
        "protein a": "Staphylococcus aureus cell wall surface protein that binds the Fc region of IgG immunoglobulins backwards, preventing opsonophagocytosis.",
        "staphylococcus pseudointermedius": "Major opportunistic Gram-positive pathogen of canines causing pyoderma, otitis externa, wound infections, and canine osteomyelitis.",
        "streptolysin o": "Oxygen-labile, cholesterol-dependent pore-forming cytolysin secreted by Group A and C streptococci; used in ASO titer serology.",
        "streptolysin s": "Oxygen-stable, non-antigenic peptide cytolysin of Streptococcus pyogenes responsible for visible beta-hemolysis on blood agar plates.",
        "lancefield grouping": "Serological classification system categorizing beta-hemolytic streptococci (Groups A through V) based on specific cell wall C-carbohydrate antigens.",
        "internalin": "Surface leucine-rich repeat proteins (InlA, InlB) of Listeria monocytogenes that bind E-cadherin and Met receptors to trigger cell invasion.",
        "listeriolysin o": "Pore-forming, cholesterol-dependent cytolysin of Listeria monocytogenes with acidic pH optimum enabling escape from host phagolysosomes.",
        "shiga toxin": "AB5 subunit holotoxin produced by STEC/EHEC that cleaves 28S rRNA, shutting down protein synthesis in microvascular endothelial cells.",
        "atrophic rhinitis": "Swine respiratory disease caused by synergistic infection of Bordetella bronchiseptica and dermonecrotic toxigenic Pasteurella multocida type D.",
        "mallein test": "Diagnostic allergic hypersensitivity test in equines for Glanders; performed via intrapalpebral injection of sterile Burkholderia mallei protein extract.",
        "pullorum disease": "Severe septicemic disease ('bacillary white diarrhea') of young poultry chicks under 3 weeks caused by Salmonella enterica serovar Pullorum.",
        "fowl typhoid": "Acute or chronic septicemic disease of growing and adult chickens and turkeys caused by non-motile Salmonella enterica serovar Gallinarum.",
        "kauffmann-white scheme": "Comprehensive serological classification system classifying Salmonella enterica into over 2,500 serovars based on O (somatic) and H (flagellar) antigens.",
        "swarming phenomenon": "Rapid, coordinated, wave-like migration of hyper-flagellated elongated swarm cells of Proteus species across moist agar surfaces forming concentric rings.",
        "urease test": "Biochemical test detecting bacterial production of urease enzyme which hydrolyses urea to alkaline ammonia, turning Stuart's broth bright pink.",
        "pyocyanin": "Blue-green phenazine pigment produced by Pseudomonas aeruginosa that generates reactive oxygen species, paralyzing host mucosal cilia.",
        "pyoverdine": "Yellow-green water-soluble fluorescent siderophore produced by Pseudomonas aeruginosa under iron-deficient conditions.",
        "melioidosis": "Zoonotic pyogranulomatous disease of sheep, goats, and pigs caused by soil saprophyte Burkholderia pseudomallei ('Whitmore's disease').",
        "shipping fever": "Pneumonic pasteurellosis in transported beef and dairy cattle caused by Mannheimia haemolytica following stress and viral preconditioning.",
        "leukotoxin": "Potent RTX-cytotoxin secreted by Mannheimia haemolytica that selectively lyses bovine ruminant neutrophils and alveolar macrophages.",
        "glasser's disease": "Infectious polyserositis, polyarthritis, and meningitis of young nursery piglets caused by Glaesserella (Haemophilus) parasuis.",
        "milk ring test": "Herd screening serological test for bovine brucellosis using stained Brucella abortus antigen mixed with whole milk; positive shows blue cream ring.",
        "abortus bang ring test": "Alternative designation for the Milk Ring Test (ABRT), an internationally recognized screening tool for dairy herd brucellosis.",
        "microscopic agglutination test": "Gold-standard serological test (MAT) for animal leptospirosis using live Leptospira serovar cultures incubated with serial serum dilutions.",
        "avian spirochaetosis": "Tick-borne septicemic disease of gallinaceous birds caused by Borrelia anserina transmitted by the soft tick Argas persicus.",
        "swine dysentery": "Severe mucohemorrhagic diarrheal disease of growing-finishing pigs targeting the caecum and colon, caused by Brachyspira hyodysenteriae.",
        "chlamydia psittaci": "Obligate intracellular bacterium causing avian chlamydiosis (psittacosis / ornithosis) and severe zoonotic atypical pneumonia in humans.",
        "elementary body": "Small (0.3 um), rigid, metabolically inert, infectious extracellular form of Chlamydia adapted for survival and host-to-host transmission.",
        "reticulate body": "Larger (1.0 um), fragile, metabolically active, non-infectious intracellular replicative form of Chlamydia dividing within cytoplasmic inclusions.",
        "black disease": "Infectious necrotic hepatitis of sheep caused by Clostridium novyi type B spores germinating in hepatic tissue damaged by migrating Fasciola flukes.",
        "thallus": "Vegetative body or soma of a fungus, typically composed of a macroscopic mass of thread-like hyphae forming a mycelium.",
        "pseudohypha": "Chain of elongated fungal yeast cells produced by incomplete budding where individual cells remain constricted at septal junctions.",
        "septate hypha": "Fungal hypha divided into distinct individual cellular compartments by cross-walls (septa) containing central communicating pores.",
        "non-septate hypha": "Coenocytic, multinucleated fungal hypha devoid of cross-walls, characteristic of Zygomycetes (Mucor, Rhizopus).",
        "conidiophore": "Specialized aerial hyphal stalk or branch bearing asexual non-motile fungal spores (conidia) at its apex or sides.",
        "sporangium": "Sac-like vegetative structure enclosing multiple asexual endospores (sporangiospores) produced by Zygomycetes.",
        "sterigma": "Small, slender pointed peg-like projection on a basidium or conidiogenous cell that bears a fungal spore.",
        "phialide": "Vase- or flask-shaped conidiogenous cell that produces conidia in basipetal succession without increasing in length (e.g. Aspergillus, Penicillium).",
        "macroconidia": "Large, multicellular, complex asexual fungal spores of dermatophytes, often spindle-shaped (Microsporum) or club-shaped (Trichophyton).",
        "microconidia": "Small, single-celled, spherical or pyriform asexual fungal spores borne singly or in clusters on dermatophytic hyphae.",
        "ectothrix": "Pattern of fungal hair invasion where dermatophyte arthroconidia form a dense mosaic sheath on the exterior cuticle surface of the hair shaft.",
        "endothrix": "Pattern of fungal hair invasion where dermatophyte arthroconidia develop entirely inside the hair shaft cortex without external sheath.",
        "wood's lamp": "Filtered ultraviolet light source (wavelength ~365 nm) used to detect apple-green fluorescence of Microsporum canis infected animal hairs.",
        "trichophyton verrucosum": "Zoophilic dermatophyte requiring inositol and thiamine, causing thick asbestos-like, crusty ringworm lesions in calves and cattle.",
        "trichophyton mentagrophytes": "Zoophilic dermatophyte with spiral hyphae and grape-like microconidia causing inflammatory ringworm in dogs, horses, and rodents.",
        "microsporum gypseum": "Geophilic dermatophyte with large, symmetrical, thin-walled, rough-surfaced macroconidia causing ringworm in dogs exposed to soil.",
        "spherule": "Large, thick-walled, spherical parasitic tissue structure (20-100 um) of Coccidioides filled with hundreds of infectious endospores.",
        "mycetoma": "Chronic granulomatous subcutaneous fungal infection characterized by localized swelling, draining sinuses, and discharge of pigmented fungal grains.",
        "guttural pouch mycosis": "Life-threatening equine fungal infection of the guttural pouch roof (Aspergillus) eroding internal carotid artery to cause fatal epistaxis.",
        "t-2 toxin": "Highly cytotoxic type-A trichothecene mycotoxin produced by Fusarium sporotrichioides causing severe dermal necrosis and immunosuppression.",
        "plasmid": "Extrachromosomal, circular, self-replicating, double-stranded DNA molecule carrying accessory non-essential genes like antibiotic resistance.",
        "episome": "Plasmid or genetic element capable of existing autonomously in the bacterial cytoplasm or integrating reversibly into the bacterial chromosome.",
        "r-plasmid": "Resistance plasmid bearing genes that encode enzymes (e.g. beta-lactamases, aminoglycoside-modifying enzymes) inactivating antibiotics.",
        "f-plasmid": "Fertility plasmid encoding sex pilus synthesis and machinery for horizontal genetic transfer via bacterial conjugation.",
        "transposon": "Mobile genetic element ('jumping gene') carrying terminal inverted repeats and transposase gene, capable of translocating between DNA replicons.",
        "insertion sequence": "Simplest type of transposable element carrying only the transposase gene bounded by inverted repeat sequences without phenotypic marker genes.",
        "conjugation": "Horizontal transfer of genetic material between bacterial cells requiring direct physical cell-to-cell contact via a sex pilus.",
        "transduction": "Transfer of bacterial chromosomal or plasmid DNA from donor to recipient cell mediated by a bacteriophage vector.",
        "generalized transduction": "Accidental packaging of arbitrary fragments of host bacterial DNA into a bacteriophage capsid during lytic cycle viral assembly.",
        "specialized transduction": "Transfer of specific, restricted host chromosomal genes adjacent to the prophage integration site due to imprecise prophage excision.",
        "blue-white screening": "Recombinant selection technique where insertional disruption of the lacZ-alpha gene in cloning vectors leaves recombinant colonies white on X-gal agar.",
        "multiple cloning site": "Engineered short region within a cloning vector containing numerous unique restriction enzyme recognition sites for inserting foreign DNA.",
        "reporter gene": "Gene encoding an easily measurable and assayable protein product (e.g. GFP, beta-galactosidase, luciferase) attached to a promoter of interest.",
        "gfp": "Green Fluorescent Protein from Aequorea victoria that fluoresces bright green under blue/UV light without requiring external chemical substrates.",
        "nucleic acid hybridization": "Annealing of single-stranded labeled DNA or RNA probe to complementary target nucleotide sequences via hydrogen bonding.",
        "multiplex pcr": "PCR amplification variant utilizing multiple sets of primer pairs within a single reaction tube to simultaneously amplify several distinct target genes.",
        "nested pcr": "Modified PCR strategy using two sequential primer pairs (outer and inner) to dramatically increase target specificity and diagnostic sensitivity.",
        "cycle threshold": "In real-time qPCR, the fractional cycle number at which the amplified fluorescent signal crosses a statistically defined background threshold line.",
        "melting curve analysis": "Post-qPCR fluorometric dissociation step that verifies target amplicon identity and purity by tracking fluorescence decay during gradual heating.",
        "next generation sequencing": "High-throughput, parallel DNA sequencing technologies (Illumina, Ion Torrent) capable of sequencing millions of small fragments simultaneously.",
        "illumina sequencing": "Next-generation sequencing platform based on reversible dye-terminators and bridge amplification on flow-cell glass slides.",
        "nanopore sequencing": "Third-generation direct single-molecule real-time sequencing measuring ionic current alterations as single DNA strands transit protein nanopores.",
        "open reading frame": "Continuous nucleotide sequence beginning with a translation start codon (AUG) and ending with a stop codon without interrupting stop codons.",
        "metagenomics": "Direct molecular analysis and genomic sequencing of total microbial DNA extracted directly from environmental or animal clinical samples.",
        "subunit vaccine": "Vaccine formulation containing only isolated, purified, non-viable, immunogenic microbial proteins rather than whole pathogens.",
        "innate immunity": "Immediate, non-specific frontline host defense mechanisms present at birth, including anatomical barriers, phagocytes, complement, and defensins.",
        "adaptive immunity": "Antigen-specific, inducible host defense mediated by B and T lymphocytes, characterized by clonal expansion, fine specificity, and lifelong memory.",
        "pathogen-associated molecular patterns": "Conserved, invariant molecular signatures shared by microbial classes (e.g. LPS, peptidoglycan, flagellin, dsRNA) recognized by host PRRs.",
        "pattern recognition receptors": "Germline-encoded host cell receptors (e.g. Toll-like receptors, NOD-like receptors) that bind microbial PAMPs to initiate innate immune responses.",
        "toll-like receptors": "Evolutionarily conserved family of transmembrane pattern recognition receptors (TLR1 through TLR10) that recognize distinct microbial components.",
        "respiratory burst": "Rapid, oxygen-dependent metabolic surge in activated neutrophils and macrophages generating toxic reactive oxygen intermediates (O2-, H2O2, HOCl).",
        "natural killer cells": "Large granular cytotoxic innate lymphocytes lacking specific BCRs and TCRs that destroy virus-infected and neoplastic cells lacking MHC Class I.",
        "dendritic cells": "Professional, highly branched antigen-presenting cells specialized in processing foreign antigens and migrating to lymph nodes to activate naive T-cells.",
        "heterophil": "Avian, reptilian, and lagomorph polymorphonuclear leukocyte functional equivalent of the mammalian neutrophil, containing prominent eosinophilic granules.",
        "primary lymphoid organs": "Anatomical sites of lymphocyte development and maturation independent of foreign antigen (bone marrow and thymus in mammals; Bursa of Fabricius in birds).",
        "secondary lymphoid organs": "Organized peripheral lymphoid tissues (spleen, lymph nodes, Peyer's patches) where mature lymphocytes encounter and respond to foreign antigens.",
        "harderian gland": "Accessory lacrimal gland situated behind avian orbits packed with plasma cells, acting as a critical site for local ocular mucosal antibody production.",
        "mucosal-associated lymphoid tissue": "Diffuse unencapsulated lymphoid aggregations (MALT) lining the respiratory, gastrointestinal, and urogenital tracts providing barrier defense.",
        "regulatory t cells": "Specialized CD4+CD25+FoxP3+ T-cell subset that actively suppresses autoreactive immune responses and maintains peripheral self-tolerance.",
        "th1 response": "Cell-mediated inflammatory immune profile driven by IL-12 and IFN-gamma, activating macrophages and CD8+ cytotoxic T-cells against intracellular pathogens.",
        "th2 response": "Humoral-dominated immune profile driven by IL-4, IL-5, and IL-13, stimulating B-cell proliferation, class-switching to IgE, and eosinophil activation.",
        "gamma-delta t cells": "T-lymphocyte subset bearing gamma-delta TCR chains, highly abundant in ruminants and pigs (up to 60%), mediating early non-MHC-restricted mucosal defense.",
        "class switching": "Biological process whereby stimulated B-cells change antibody isotype production (from IgM to IgG, IgA, or IgE) without altering antigen specificity.",
        "affinity maturation": "Progressive increase in antibody binding affinity for target antigen over time during an immune response, driven by somatic hypermutation in germinal centers.",
        "secretory component": "Polypeptide cleavage fragment of the polymeric immunoglobulin receptor (pIgR) remaining attached to dimeric IgA, protecting it from mucosal proteolysis.",
        "j-chain": "Small 15-kDa joining polypeptide required for the assembly and polymeric stabilization of pentameric IgM and dimeric IgA immunoglobulins.",
        "complement classical pathway": "Cascade of complement activation initiated by the binding of C1q to antigen-bound IgM or IgG immune complexes on cell surfaces.",
        "complement alternative pathway": "Antibody-independent complement activation pathway triggered directly by spontaneous low-level C3 hydrolysis on foreign microbial surfaces.",
        "complement lectin pathway": "Antibody-independent complement activation triggered by host mannose-binding lectin (MBL) binding terminal mannose residues on bacterial walls.",
        "virus neutralization test": "Highly specific serological assay where serial serum dilutions are incubated with virus; loss of viral infectivity or cytopathic effect indicates neutralizing antibodies.",
        "helical symmetry": "Viral capsid architecture where capsomeres are arranged spirally around a central coil of nucleic acid, forming a hollow cylindrical rod or filament.",
        "icosahedral symmetry": "Viral capsid morphology composed of 20 equilateral triangular facets and 12 vertices providing optimal thermodynamic volume for enclosing viral genomes.",
        "eclipse period": "Phase during viral replication immediately following intracellular uncoating during which infectious virus cannot be detected inside the host cell.",
        "burst size": "Average yield of newly assembled, infectious virions released from a single infected host cell upon completion of the lytic replication cycle.",
        "hemagglutinin": "Surface spike glycoprotein of viruses (Influenza, Newcastle disease) that binds sialic acid on host cell receptors and clumps erythrocytes.",
        "neuraminidase": "Viral receptor-destroying enzyme that cleaves terminal sialic acid from host cell glycoproteins, releasing newly formed budding virions.",
        "fusion protein": "Class I viral surface glycoprotein (Paramyxoviridae) that mediates direct fusion of viral envelope with host cell membrane at neutral pH.",
        "matrix protein": "Structural viral protein lining the inner surface of viral envelope, providing mechanical support and coordinating viral core assembly with budding.",
        "rna-dependent rna polymerase": "Viral enzyme essential for replication and transcription of RNA viruses, lacking proofreading ability and driving high mutation rates.",
        "provirus": "Double-stranded DNA copy of a retroviral genome permanently integrated into the host cell nuclear chromosome by viral integrase.",
        "viral interference": "Phenomenon where pre-existing infection of a host cell by one virus prevents or blocks superinfection by a second homologous or heterologous virus.",
        "defective interfering particles": "Sub-genomic viral mutants that require homologous wild-type helper virus to replicate, competing for machinery and attenuating disease severity.",
        "latent viral infection": "Type of viral persistence where viral genome remains dormant within host cells without producing infectious virions until reactivation occurs.",
        "slow viral infection": "Chronic viral disease with prolonged incubation period extending over months or years, followed by progressive, fatal illness (e.g. Visna-Maedi).",
        "vesicular stomatitis": "Vesicular rhabdoviral disease affecting horses, cattle, and swine with oral lesions clinically indistinguishable from Foot-and-Mouth Disease.",
        "swine vesicular disease": "Contagious enteroviral disease affecting only swine, producing coronary band and snout vesicles clinically mimicking Foot-and-Mouth Disease.",
        "coggins test": "Agar Gel Immunodiffusion (AGID) reference diagnostic test detecting serum antibodies against p26 antigen of Equine Infectious Anemia Virus (EIAV).",
        "lumpy skin disease": "Transboundary poxviral disease of cattle (Capripoxvirus) transmitted by biting insects, characterized by widespread skin nodules and lymphadenopathy.",
        "aujeszky's disease": "'Pseudorabies'; porcine herpesvirus causing reproductive failure in sows, fatal encephalitis in piglets, and 'mad itch' in dead-end host cattle/dogs.",
        "infectious canine hepatitis": "Acute adenovirus (CAV-1) infection of dogs causing centrilobular liver necrosis, gallbladder edema, and transient corneal clouding ('blue eye').",
        "pleomorphism": "Variation in size and shape of bacterial cells within a single pure culture due to lack of rigid cell wall (e.g. Mycoplasma) or nutritional conditions.",
        "tyndallization": "Intermittent fractional steam sterilization at 100°C for 30 minutes on three successive days to destroy both vegetative cells and germinating endospores.",
        "macconkey agar": "Selective and differential culture medium with bile salts and crystal violet inhibiting Gram-positives, using neutral red to detect lactose fermentation.",
        "blood agar": "Enriched differential medium containing 5–10% defibrinated mammalian blood used to detect alpha, beta, and gamma hemolytic patterns.",
        "chocolate agar": "Enriched medium prepared by heating blood agar to lyse red cells, releasing hemin (factor X) and NAD (factor V) for fastidious pathogens like Haemophilus.",
        "mannitol salt agar": "Selective differential medium containing 7.5% NaCl favoring halotolerant Staphylococci, with phenol red indicating mannitol fermentation.",
        "brilliant green agar": "Highly selective culture medium for Salmonella isolation from feces, using brilliant green dye to inhibit coliforms and other non-salmonellae.",
        "selenite f broth": "Enrichment liquid broth containing sodium selenite that inhibits coliforms while promoting the initial recovery of Salmonella from clinical fecal samples.",
        "tetrathionate broth": "Selective enrichment medium for Salmonella utilizing tetrathionate, bile salts, and iodine to suppress normal intestinal commensal flora.",
        "simmons citrate agar": "Synthetic defined differential medium testing bacterial ability to utilize sodium citrate as the sole carbon source and ammonium salts as nitrogen.",
        "triple sugar iron agar": "Multi-test slant medium (TSI) detecting carbohydrate fermentation (glucose, lactose, sucrose), gas production, and hydrogen sulfide (H2S) generation.",
        "indole test": "Biochemical assay detecting bacterial enzyme tryptophanase which converts amino acid tryptophan into indole, visualized by Kovac's reagent (cherry-red ring).",
        "methyl red test": "Biochemical assay testing mixed acid fermentation pathway; persistent low pH (< 4.4) keeps methyl red indicator bright red upon addition.",
        "voges-proskauer test": "Biochemical test detecting acetoin (acetylmethylcarbinol), an intermediate in the 2,3-butanediol fermentation pathway, using alpha-naphthol and KOH.",
        "coagulase-negative staphylococci": "Non-pathogenic or opportunistic Staphylococci (e.g. S. epidermidis) lacking coagulase enzyme, forming biofilms on veterinary medical devices.",
        "necrotic enteritis": "Severe clostridial enterotoxemic disease of broiler chickens caused by Clostridium perfringens type A or C producing NetB pore-forming toxin.",
        "braxy": "Acute, fatal abomasitis in young weaned sheep caused by Clostridium septicum proliferating in the abomasal wall following ingestion of frozen pasture.",
        "malignant edema": "Acute, wound-associated gas gangrene in livestock characterized by crepitant subcutaneous edema, caused by Clostridium septicum, chauvoei, or novyi.",
        "bacillary hemoglobinuria": "Acute fatal clostridial disease of cattle ('Redwater') caused by Clostridium haemolyticum beta-toxin following liver damage by migrating liver flukes.",
        "tyzzer's disease": "Acute fatal enterohepatic disease of foals and rodents caused by intracellular filamentous bacterium Clostridium piliforme (spores stain with silver).",
        "contagious caprine pleuropneumonia": "Devastating mycoplasmal disease of goats (CCPP) caused by Mycoplasma capricolum subsp. capripneumoniae, causing unilateral marbled lung consolidation.",
        "moraxella bovis": "Fastidious Gram-negative fimbriated coccobacillus causing Infectious Bovine Keratoconjunctivitis ('pinkeye') via RTX-toxin corneal epithelial lysis.",
        "borrelia theileri": "Tick-borne spirochaete transmitted by Rhipicephalus ticks causing mild relapsing fever and anemia in cattle and horses.",
        "campylobacter fetus fetus": "Oral pathogen of sheep causing bacteremia, necrotic placentitis, third-trimester abortions, and pathognomonic fetal liver target lesions.",
        "campylobacter fetus venerealis": "Venereal bacterial pathogen of cattle causing endometritis, early embryonic mortality, and temporary herd infertility via carrier bulls.",
        "taylorella equigenitalis": "Microaerophilic coccobacillus causing Contagious Equine Metritis (CEM) in mares with profuse vaginal discharge, carried asymptomatically by stallions.",
        "mycoplasma bovis": "Major mycoplasmal pathogen of cattle causing refractory chronic bronchopneumonia, caseonecrotic lung lesions, polyarthritis, and unresponsive mastitis.",
        "mycoplasma agalactiae": "Causative agent of Contagious Agalactia in sheep and goats, causing triad of purulent mastitis, arthritis, and keratoconjunctivitis.",
        "coxiella burnetii": "Extremely resilient zoonotic intracellular bacterium causing Q fever, targeting ruminant trophoblasts to trigger late-term abortion and massive shedding.",
        "dermatophilus congolensis": "Gram-positive filamentous actinomycete with motile zoospores causing exudative epidermitis, paintbrush crusts in horses ('rain scald'), and lumpy wool in sheep.",
        "pasteurella canis": "Commensal oral bacterium of dogs and cats commonly inoculated through bite wounds, causing cellulitis, phlegmon, and septicemia in humans and animals.",
        "bacteroides fragilis": "Obligate anaerobic Gram-negative rod of normal intestinal flora with polysaccharide capsule, producing opportunistic intra-abdominal abscesses and peritonitis.",
        "actinobacillus pleuropneumoniae": "Major swine pathogen (APP) producing RTX Apx toxins, causing peracute fibrinous and necrotizing hemorrhagic pleuropneumonia.",
        "glaesserella parasuis": "Gram-negative bacterium causing Glasser's disease in nursery piglets characterized by severe fibrinous polyserositis, polyarthritis, and meningitis.",
        "lawsonia intracellularis": "Obligate intracellular bacterium of intestinal crypt enterocytes causing Porcine Proliferative Enteropathy ('garden hose ileum' / ileitis) in pigs.",
        "microsporum canis": "Zoophilic dermatophyte producing 6-12 celled, thick-walled, rough, spindle-shaped macroconidia, the principal cause of ringworm in cats and dogs.",
        "coccidioidomycosis": "'Valley Fever'; deep granulomatous mycosis of dogs in arid regions caused by inhalation of Coccidioides arthroconidia that form giant endospore-filled spherules.",
        "blastomycosis": "Chronic pyogranulomatous systemic mycosis of dogs and humans caused by Blastomyces dermatitidis, forming characteristic broad-based budding yeasts in lungs and skin.",
        "histoplasmosis": "Systemic granulomatous mycosis caused by Histoplasma capsulatum, involving reticuloendothelial cells and gut-associated lymphoid tissue (severe canine diarrhea).",
        "phaeohyphomycosis": "Opportunistic fungal infection caused by dematiaceous (darkly pigmented) fungi whose cell walls contain melanin, forming pigmented hyphae in tissues.",
        "hyalohyphomycosis": "Invasive fungal infection caused by non-pigmented (hyaline) moulds in tissues without grain or sulfur formation (e.g. Fusarium, Paecilomyces).",
        "mycotoxicosis": "Non-infectious, non-contagious toxic disease of animals caused by ingestion of toxic fungal secondary metabolites produced on feedstuffs or grains.",
        "citrinin": "Nephrotoxic mycotoxin produced by Penicillium and Aspergillus species that contaminates cereal grains, acting synergistically with ochratoxin A.",
        "slaframine": "Indolizidine alkaloid mycotoxin ('slobber factor') produced by Rhizoctonia leguminicola on red clover, stimulating excessive salivation in horses.",
        "stachybotryotoxicosis": "Toxicosis caused by macrocyclic trichothecenes of Stachybotrys chartarum growing on damp straw, causing oral ulcerations, hemorrhage, and leukopenia.",
        "pithomycotoxicosis": "'Facial eczema' of sheep and cattle caused by sporidesmin produced by Pithomyces chartarum, inducing bile duct necrosis and secondary photosensitization.",
        "macrocyclic trichothecenes": "Potent protein synthesis-inhibiting mycotoxins produced by Myrothecium and Stachybotrys causing severe necrotizing gastroenteritis and coagulopathies.",
        "site-directed mutagenesis": "Molecular biotechnology technique used to make specific, intentional, targeted changes to the nucleotide sequence of a cloned gene or vector.",
        "sybr green": "Asymmetrical cyanine fluorophore dye that binds non-specifically to the minor groove of double-stranded DNA during real-time quantitative PCR.",
        "taqman probe": "Fluorogenic oligonucleotide probe with 5'-reporter and 3'-quencher dyes; cleaved by Taq polymerase 5'-to-3' exonuclease activity during qPCR.",
        "crispr-cas9": "RNA-guided prokaryotic adaptive immune defense system engineered for precise, site-specific targeted gene editing and genomic modification in animals.",
        "guide rna": "Engineered synthetic RNA construct consisting of crRNA and tracrRNA that directs Cas9 endonuclease to cleavage sites via complementary base pairing.",
        "pam sequence": "Protospacer Adjacent Motif; short 2-6 base pair DNA sequence immediately following the Cas9 target site strictly essential for Cas9 cleavage.",
        "pulsed-field gel electrophoresis": "Variant of agarose gel electrophoresis using alternating multidirectional electric fields to separate extremely large megabase bacterial DNA fragments.",
        "dna microarray": "High-throughput hybridization platform with thousands of microscopic nucleic acid spots bound to a glass slide, assaying whole-transcriptome expression.",
        "plasmid curing": "Process of eliminating bacterial plasmids through chemical treatment (acridine orange, ethidium bromide) or elevated temperature to determine plasmid-borne traits.",
        "bacteriophage typing": "Identification and epidemiological tracing of bacterial isolates (e.g. Salmonella, Staphylococcus) based on their susceptibility patterns to specific phage sets.",
        "recombinant subunit vaccine": "Vaccine produced by expressing immunogenic microbial surface protein genes in foreign hosts (yeast, insect cells, E. coli) without infectious agents.",
        "reverse genetics": "Molecular virology method allowing de novo generation of infectious animal viruses from full-length cloned complementary DNA (cDNA) plasmids.",
        "clonal selection": "Core immunological theory postulating that antigen exposure selects and stimulates only those rare lymphocytes already possessing matching specific receptors.",
        "postzone phenomenon": "Serological reaction failure (false-negative) caused by vast excess of antigen relative to antibody, preventing lattice cross-linking in precipitation tests.",
        "indirect coombs test": "Antiglobulin serological test detecting incomplete, non-agglutinating circulating antibodies in patient serum by incubating with red cells and anti-IgG.",
        "direct coombs test": "Antiglobulin test used to detect in vivo autoimmune antibodies or complement already bound to patient erythrocytes (e.g. in canine IMHA).",
        "plaque reduction neutralization": "Gold-standard serological assay (PRNT) quantifying virus-neutralizing antibody titer by measuring 50% reduction in viral plaque formation.",
        "fluorescent antibody test": "Rapid diagnostic serological technique using fluorescein-conjugated antibodies (FAT) to visualize microbial antigens directly in infected tissue smears.",
        "indirect fluorescent antibody": "Two-step serological technique (IFAT) detecting patient serum antibodies by binding to fixed pathogen antigens followed by labeled anti-species secondary antibody.",
        "lateral flow assay": "Rapid strip immunochromatographic diagnostic test (LFA) utilizing capillary action on nitrocellulose membranes for point-of-care antigen/antibody detection.",
        "differentiating infected from vaccinated animals": "The DIVA principle; vaccination strategy using marker vaccines and matching companion diagnostic tests to distinguish vaccinated from field-infected stock.",
        "bovine leukocyte adhesion deficiency": "Fatal autosomal recessive genetic disease of Holstein calves (BLAD) causing CD18 beta-2 integrin defect, resulting in extreme neutrophilia without pus formation.",
        "immune tolerance": "State of unresponsiveness of the immune system to specific antigens, particularly self-antigens, preventing autoimmune destruction.",
        "cross-reactivity": "Binding of an antibody or antigen receptor to an epitope structurally similar to, but distinct from, the original immunizing antigen.",
        "superantigen": "Microbial toxin that binds directly to the outer surface of MHC-II and TCR Vβ without processing, non-specifically triggering massive cytokine storms.",
        "neonatal isoerythrolysis": "Immune-mediated hemolytic disease of newborn foals and calves occurring when maternal colostral alloantibodies destroy the neonate's red blood cells.",
        "seroconversion": "Development of detectable specific antibodies in serum in response to primary infection or vaccination, usually marked by a four-fold titer rise.",
        "plaque forming unit": "Unit of measurement (PFU) denoting the quantity of infectious viral particles capable of forming a discrete circular clearing zone in a cell monolayer.",
        "bovine viral diarrhea": "Economically devastating pestiviral disease of cattle (BVDV) causing mucosal ulcerations, severe immunosuppression, persistent fetal infection, and scours.",
        "classical swine fever": "Contagious transboundary pestiviral disease of pigs (CSFV / Hog Cholera) causing high fever, hemorrhages, button ulcers, and splenic infarctions.",
        "border disease": "'Hairy shaker disease'; congenital pestiviral infection of sheep and goats characterized by rhythmic muscular tremors, hairy fleeces, and skeletal abnormalities.",
        "bovine leukemia virus": "Deltaretrovirus of cattle causing Enzootic Bovine Leukosis, characterized by persistent lymphocytosis and multicentric B-cell lymphosarcoma in adult cattle.",
        "caprine arthritis encephalitis": "Chronic lentiviral infection of goats (CAEV) causing proliferative carpal arthritis ('big knee'), indurative mastitis ('hard bag'), and leukoencephalitis.",
        "maedi-visna virus": "Ovine lentivirus causing chronic, progressive, fatal interstitial pneumonia ('Maedi') and demyelinating leukoencephalomyelitis ('Visna') in adult sheep.",
        "feline calicivirus": "Highly contagious respiratory and oral pathogen of cats (FCV) causing painful oral lingual ulcers, rhinitis, conjunctivitis, and limping kitten syndrome.",
        "bovine ephemeral fever": "'Three-day sickness'; vector-borne rhabdovirus of cattle causing sudden biphasic fever, shifting lameness, and serofibrinous polysynovitis with rapid recovery.",
        "duck viral hepatitis": "Peracute picornaviral infection of ducklings under 3 weeks causing rapid opisthotonos ('viewing the stars') and punctate ecchymotic liver hemorrhages.",
        "feline panleukopenia": "Severe, highly contagious parvoviral disease of cats (FPV) causing fever, intractable vomiting, bloody diarrhea, and profound leukopenia.",
        "canine parvovirus": "Small, non-enveloped DNA virus (CPV-2) causing severe hemorrhagic enteritis and acute myocarditis in young puppies.",
        "porcine circovirus": "Smallest known single-stranded circular DNA virus (PCV-2) causing Postweaning Multisystemic Wasting Syndrome (PMWS) and porcine dermatitis and nephropathy.",
        "chicken anemia virus": "Gyrovirus of the family Anelloviridae causing aplastic anemia, lymphoid atrophy, and severe intramuscular hemorrhages in young chicks.",
        "equine viral arteritis": "Arterivirus of horses (EAV) causing necrotizing arteritis, fever, dependent edema, and late abortion storms in pregnant mares."
    },

    _regex: null,
    _lookup: null,
    _scrollHooked: false,

    _buildIndex() {
        this._lookup = {};
        const termKeys = Object.keys(this.terms);
        // Sort descending by string length to match multi-word expressions first
        termKeys.sort((a, b) => b.length - a.length);

        termKeys.forEach(t => {
            this._lookup[t.toLowerCase()] = this.terms[t];
        });

        // Safe regex escaping
        const escaped = termKeys.map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
        this._regex = new RegExp(`\\b(${escaped.join('|')})\\b`, 'gi');
    },

    _positionTooltip(termSpan) {
        const rect = termSpan.getBoundingClientRect();
        const vw = window.innerWidth;
        const vh = window.innerHeight;
        const margin = 12;

        const ttWidth = Math.min(320, vw - margin * 2);
        let left = rect.left + rect.width / 2 - ttWidth / 2;
        let top = rect.bottom + 8;
        const ttEstHeight = 90;

        if (left + ttWidth > vw - margin) left = vw - ttWidth - margin;
        if (left < margin) left = margin;

        if (top + ttEstHeight > vh - margin) {
            const above = rect.top - ttEstHeight - 8;
            if (above >= margin) top = above;
        }

        termSpan.style.setProperty('--tt-left', left + 'px');
        termSpan.style.setProperty('--tt-top', top + 'px');
        termSpan.style.setProperty('--tt-width', ttWidth + 'px');
    },

    // Safely decorate text nodes without touching interactive or existing nodes
    decorate(root) {
        if (!root) return;
        if (!this._regex) this._buildIndex();

        const SKIP = new Set(['A', 'BUTTON', 'INPUT', 'TEXTAREA', 'SELECT', 'SCRIPT', 'STYLE', 'CODE', 'PRE']);
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
            acceptNode(node) {
                if (!node.textContent.trim()) return NodeFilter.FILTER_REJECT;
                let p = node.parentNode;
                while (p) {
                    if (!p.tagName) break;
                    if (SKIP.has(p.tagName)) return NodeFilter.FILTER_REJECT;
                    if (p.classList && p.classList.contains('gloss-term')) return NodeFilter.FILTER_REJECT;
                    p = p.parentNode;
                }
                return NodeFilter.FILTER_ACCEPT;
            }
        });

        const targets = [];
        let n;
        while ((n = walker.nextNode())) targets.push(n);

        targets.forEach((textNode) => {
            const text = textNode.textContent;
            if (!this._regex.test(text)) return;
            this._regex.lastIndex = 0;

            const frag = document.createDocumentFragment();
            let lastIdx = 0;
            let m;
            while ((m = this._regex.exec(text)) !== null) {
                if (m.index > lastIdx) {
                    frag.appendChild(document.createTextNode(text.slice(lastIdx, m.index)));
                }
                const span = document.createElement('span');
                span.className = 'gloss-term';
                span.textContent = m[0];
                const def = this._lookup[m[0].toLowerCase()] || '';
                span.dataset.def = def;
                span.setAttribute('tabindex', '0');
                span.setAttribute('role', 'button');
                span.setAttribute('aria-label', `Definition of ${m[0]}: ${def}`);

                const onShow = (e) => this._positionTooltip(e.currentTarget);
                span.addEventListener('mouseenter', onShow);
                span.addEventListener('focus', onShow);
                span.addEventListener('touchstart', onShow, { passive: true });

                // Double-click to pronounce aloud via SpeechSynthesis
                span.addEventListener('dblclick', (e) => {
                    e.preventDefault();
                    if (window.app && typeof window.app.speak === 'function') {
                        window.app.speak(e.currentTarget.textContent);
                    }
                });

                frag.appendChild(span);
                lastIdx = m.index + m[0].length;
            }

            if (lastIdx < text.length) {
                frag.appendChild(document.createTextNode(text.slice(lastIdx)));
            }

            textNode.parentNode.replaceChild(frag, textNode);
        });

        if (!this._scrollHooked) {
            this._scrollHooked = true;
            const reposition = () => {
                const active = document.querySelector('.gloss-term:hover, .gloss-term:focus');
                if (active) this._positionTooltip(active);
            };
            window.addEventListener('scroll', reposition, { passive: true, capture: true });
            window.addEventListener('resize', reposition, { passive: true });
        }
    },

    define(term) {
        if (!this._lookup) this._buildIndex();
        return this._lookup[term.toLowerCase()] || null;
    },

    // Return all terms formatted with category for Library UI and Search Indexer
    getAll() {
        const result = [];
        const catMap = {};
        for (const cat in this.categories) {
            this.categories[cat].forEach(t => {
                catMap[t.toLowerCase()] = cat;
            });
        }
        for (const term in this.terms) {
            result.push({
                term: term,
                def: this.terms[term],
                category: catMap[term.toLowerCase()] || 'General Microbiology'
            });
        }
        return result.sort((a, b) => a.term.localeCompare(b.term));
    }
};

if (typeof window !== 'undefined') {
    window.glossary = glossary;
}
